package com.myapp.ecommerce.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import java.util.Objects;

@DynamoDBTable(tableName = "address")
public class Address {
    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String id;

    public Address() {
    }

    @Override
    public String toString() {
        return "Address{" +
                "id='" + id + '\'' +
                ", userId='" + userId + '\'' +
                ", city='" + city + '\'' +
                ", street='" + street + '\'' +
                ", region='" + region + '\'' +
                ", CEP='" + CEP + '\'' +
                ", phone='" + phone + '\'' +
                ", complement='" + complement + '\'' +
                ", isDefault=" + isDefault +
                '}';
    }

    public String getId() {
        return id;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        Address address = (Address) o;
        return isDefault == address.isDefault && Objects.equals(id, address.id) && Objects.equals(userId, address.userId) && Objects.equals(city, address.city) && Objects.equals(street, address.street) && Objects.equals(region, address.region) && Objects.equals(CEP, address.CEP) && Objects.equals(phone, address.phone) && Objects.equals(complement, address.complement);
    }

    @Override
    public int hashCode() {
        return Objects.hash(id, userId, city, street, region, CEP, phone, complement, isDefault);
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getUserId() {
        return userId;
    }

    public void setUserId(String userId) {
        this.userId = userId;
    }

    public String getCity() {
        return city;
    }

    public void setCity(String city) {
        this.city = city;
    }

    public String getStreet() {
        return street;
    }

    public void setStreet(String street) {
        this.street = street;
    }

    public String getRegion() {
        return region;
    }

    public void setRegion(String region) {
        this.region = region;
    }

    public String getCEP() {
        return CEP;
    }

    public void setCEP(String CEP) {
        this.CEP = CEP;
    }

    public String getPhone() {
        return phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    public String getComplement() {
        return complement;
    }

    public void setComplement(String complement) {
        this.complement = complement;
    }

    public boolean isDefault() {
        return isDefault;
    }

    public void setDefault(boolean aDefault) {
        isDefault = aDefault;
    }

    public Address(String id, String userId, String city, String street, String region, String CEP, String phone, String complement, boolean isDefault) {
        this.id = id;
        this.userId = userId;
        this.city = city;
        this.street = street;
        this.region = region;
        this.CEP = CEP;
        this.phone = phone;
        this.complement = complement;
        this.isDefault = isDefault;
    }

    @DynamoDBAttribute
    private String userId;
    @DynamoDBAttribute
    private String city;
    @DynamoDBAttribute
    private String street;
    @DynamoDBAttribute
    private String region;
    @DynamoDBAttribute
    private String CEP;
    @DynamoDBAttribute
    private String phone;
    @DynamoDBAttribute
    private String complement;
    @DynamoDBAttribute
    private boolean isDefault;
}
