package com.myapp.ecommerce.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.*;

import java.util.List;
import java.util.Map;
import java.util.Objects;

@DynamoDBTable(tableName = "cart")
public class Cart {
    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String cartId;


    public String getCartId() {
        return cartId;
    }

    public void setCartId(String cartId) {
        this.cartId = cartId;
    }

    public String getUserId() {
        return userId;
    }

    public void setUserId(String userId) {
        this.userId = userId;
    }

    public double getPrice() {
        return price;
    }

    public void setPrice(double price) {
        this.price = price;
    }

    public Cart() {
    }

    @DynamoDBAttribute(attributeName = "userId")
    private String userId;

    public List<Product> getProductList() {
        return productList;
    }


    @Override
    public String toString() {
        return "Cart{" +
                "cartId='" + cartId + '\'' +
                ", userId='" + userId + '\'' +
                ", price=" + price +
                ", productList=" + productList +
                '}';
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        Cart cart = (Cart) o;
        return Double.compare(price, cart.price) == 0 && Objects.equals(cartId, cart.cartId) && Objects.equals(userId, cart.userId) && Objects.equals(productList, cart.productList);
    }

    @Override
    public int hashCode() {
        return Objects.hash(cartId, userId, price, productList);
    }

    public Cart(String cartId, String userId, double price, List<Product> productList) {
        this.cartId = cartId;
        this.userId = userId;
        this.price = price;
        this.productList = productList;
    }

    public void setProductList(List<Product> productList) {
        this.productList = productList;
    }

    @DynamoDBAttribute
    private double price;
    @DynamoDBAttribute
    private List<Product> productList;
}
