package com.myapp.ecommerce.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import java.util.Map;
import java.util.Objects;

@DynamoDBTable(tableName = "user")
public class Order {
    public String getId() {
        return id;
    }

    public Order() {
    }

    @Override
    public String toString() {
        return "Order{" +
                "id='" + id + '\'' +
                ", userId='" + userId + '\'' +
                ", isFinished=" + isFinished +
                ", status='" + status + '\'' +
                ", items=" + items +
                ", price=" + price +
                '}';
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        Order order = (Order) o;
        return isFinished == order.isFinished && Double.compare(price, order.price) == 0 && Objects.equals(id, order.id) && Objects.equals(userId, order.userId) && Objects.equals(status, order.status) && Objects.equals(items, order.items);
    }

    @Override
    public int hashCode() {
        return Objects.hash(id, userId, isFinished, status, items, price);
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getUserId() {
        return userId;
    }

    public void setUserId(String userId) {
        this.userId = userId;
    }

    public boolean isFinished() {
        return isFinished;
    }

    public void setFinished(boolean finished) {
        isFinished = finished;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public Map<String, Integer> getItems() {
        return items;
    }

    public void setItems(Map<String, Integer> items) {
        this.items = items;
    }

    public double getPrice() {
        return price;
    }

    public void setPrice(double price) {
        this.price = price;
    }

    public Order(String id, String userId, boolean isFinished, String status, Map<String, Integer> items, double price) {
        this.id = id;
        this.userId = userId;
        this.isFinished = isFinished;
        this.status = status;
        this.items = items;
        this.price = price;
    }

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String id;
    @DynamoDBAttribute
    private String userId;
    @DynamoDBAttribute
    private boolean isFinished;
    @DynamoDBAttribute
    private String status;
    @DynamoDBAttribute
    private Map<String, Integer> items;
    @DynamoDBAttribute
    private double price;

}
