package com.myapp.ecommerce.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import jakarta.validation.constraints.Email;
import jakarta.validation.constraints.NotBlank;


import java.util.Date;
import java.util.Objects;

@DynamoDBTable(tableName = "user")
public class User {
    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String userID;

    @DynamoDBAttribute
    @DynamoDBAutoGeneratedTimestamp(strategy= DynamoDBAutoGenerateStrategy.CREATE)
    private Date createdAt;

    @Override
    public String toString() {
        return "User{" +
                "userID='" + userID + '\'' +
                ", createdAt=" + createdAt +
                ", updateAt=" + updateAt +
                ", name='" + name + '\'' +
                ", phoneNumber='" + phoneNumber + '\'' +
                ", email='" + email + '\'' +
                ", password='" + password + '\'' +
                '}';
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        User user = (User) o;
        return Objects.equals(userID, user.userID) && Objects.equals(createdAt, user.createdAt) && Objects.equals(updateAt, user.updateAt) && Objects.equals(name, user.name) && Objects.equals(phoneNumber, user.phoneNumber) && Objects.equals(email, user.email) && Objects.equals(password, user.password);
    }

    @Override
    public int hashCode() {
        return Objects.hash(userID, createdAt, updateAt, name, phoneNumber, email, password);
    }

    public User(String userID, Date createdAt, Date updateAt, String name, String phoneNumber, String email, String password) {
        this.userID = userID;
        this.createdAt = createdAt;
        this.updateAt = updateAt;
        this.name = name;
        this.phoneNumber = phoneNumber;
        this.email = email;
        this.password = password;
    }

    public User(Date createdAt, Date updateAt, String name, String phoneNumber, String email, String password) {
        this.createdAt = createdAt;
        this.updateAt = updateAt;
        this.name = name;
        this.phoneNumber = phoneNumber;
        this.email = email;
        this.password = password;
    }

    @DynamoDBAttribute
    private Date updateAt;

    @DynamoDBAttribute
    @NotBlank
    private String name;

    @DynamoDBAttribute
    private String phoneNumber;

    @DynamoDBAttribute
    @Email
    private String email;

    public User() {
    }

    public String getUserID() {
        return userID;
    }


    public void setUserID(String userID) {
        this.userID = userID;
    }

    public Date getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    public Date getUpdateAt() {
        return updateAt;
    }

    public void setUpdateAt(Date updateAt) {
        this.updateAt = updateAt;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getPhoneNumber() {
        return phoneNumber;
    }

    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    @DynamoDBAttribute
    private String password;

}
